name: OSSF Scorecard

on:
  push:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:  # Define top-level permissions for the workflow
  contents: read
  security-events: write  # Required for uploading SARIF files

jobs:
  scorecard:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: ossf/scorecard-action@v2
      with:
        results_file: results.sarif
        results_format: sarif
        publish_results: true
    - uses: actions/upload-artifact@v3
      with:
        name: SARIF file
        path: results.sarif
    - name: Upload SARIF to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
