name: Shell Script Code Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  shell_lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4.1.1
    
    - name: Install ShellCheck
      run: sudo apt-get install -y shellcheck

    - name: Run ShellCheck
      run: |
        find . -name "*.sh" -print0 | xargs -0 shellcheck -f gcc

    - name: Install shfmt
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        curl -sSL https://github.com/mvdan/sh/releases/download/v3.6.0/shfmt_v3.6.0_linux_amd64 -o shfmt
        sudo chmod +x shfmt
        sudo mv shfmt /usr/local/bin/shfmt

    - name: Run shfmt
      run: |
        find . -name "*.sh" -print0 | xargs -0 shfmt -d

    - name: Upload ShellCheck Results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
