name: Shell Script Code Scan with shellharden

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  shell_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4.1.1
    
    - name: Install shellharden
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        # Install shellharden
        curl -LO https://github.com/anordal/shellharden/releases/download/v4.0.0/shellharden-linux-x86_64
        sudo chmod +x shellharden-linux-x86_64
        sudo mv shellharden-linux-x86_64 /usr/local/bin/shellharden

    - name: Run shellharden
      run: |
        mkdir -p output
        find . -name "*.sh" -print0 | xargs -0 shellharden --check > output/shellharden_results.txt

    - name: Convert shellharden Results to SARIF
      run: |
        # Create a minimal SARIF file from shellharden results
        echo '{
          "version": "2.1.0",
          "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
          "runs": [
            {
              "tool": {
                "driver": {
                  "name": "shellharden",
                  "informationUri": "https://github.com/anordal/shellharden",
                  "version": "v4.0.0"
                }
              },
              "results": [
                {
                  "ruleId": "shellharden-rule",
                  "message": {"text": "Check the shellharden results for details."},
                  "locations": [
                    {
                      "physicalLocation": {
                        "artifactLocation": {"uri": "results.txt"},
                        "region": {"startLine": 1}
                      }
                    }
                  ]
                }
              ]
            }
          ]
        }' > output/results.sarif

    - name: Upload SARIF to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: output/results.sarif
