name: Shell Script Code Scan with shellharden

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  shell_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4.1.1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl

    - name: Download shellharden
      run: |
        curl -LO https://github.com/anordal/shellharden/releases/download/v4.0.0/shellharden-linux-x86_64
        ls -l shellharden-linux-x86_64
        file shellharden-linux-x86_64 # Check the file type to ensure it's correct

    - name: Install shellharden
      run: |
        chmod +x shellharden-linux-x86_64
        mv shellharden-linux-x86_64 /usr/local/bin/shellharden
        ls -l /usr/local/bin/shellharden
        file /usr/local/bin/shellharden # Verify the installed binary type

    - name: Verify shellharden installation
      run: |
        /usr/local/bin/shellharden --version

    - name: Run shellharden
      run: |
        mkdir -p output
        find . -name "*.sh" -print0 | xargs -0 /usr/local/bin/shellharden --check > output/shellharden_results.txt || true

    - name: Upload shellharden Results
      uses: actions/upload-artifact@v4.3.1
      with:
        name: shellharden-results
        path: output/shellharden_results.txt
        retention-days: 5
